export const CREATE_PROMOTION_REQUEST = "CREATE_PROMOTION_REQUEST"
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS"
export const CREATE_PROMOTION_FAILURE = "CREATE_PROMOTION_FAILURE"

export const UPDATE_PROMOTION_REQUEST = "UPDATE_PROMOTION_REQUEST"
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS"
export const UPDATE_PROMOTION_FAILURE = "UPDATE_PROMOTION_FAILURE"

export const GET_PROMOTIONS_REQUEST = "GET_PROMOTIONS_REQUEST"
export const GET_PROMOTIONS_SUCCESS = "GET_PROMOTIONS_SUCCESS"
export const GET_PROMOTIONS_FAILURE = "GET_PROMOTIONS_FAILURE"