export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDERS_REQUEST'
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDERS_SUCCESS'
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDERS_FAILURE';

export const PLACED_ORDER_REQUEST = 'PLACED_ORDERS_REQUEST'
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDERS_SUCCESS'
export const PLACED_ORDER_FAILURE = 'PLACED_ORDERS_FAILURE';

export const DELIVERED_ORDER_REQUEST = 'DELIVERED_ORDERS_REQUEST'
export const DELIVERED_ORDER_SUCCESS = 'DELIVERED_ORDERS_SUCCESS'
export const DELIVERED_ORDER_FAILURE = 'DELIVERED_ORDERS_FAILURE'

export const CANCELED_ORDER_REQUEST = 'CANCELED_ORDER_REQUEST'
export const CANCELED_ORDER_SUCCESS = 'CANCELED_ORDERS_SUCCESS'
export const CANCELED_ORDER_FAILURE = 'CANCELED_ORDER_FAILURE'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDERS_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDERS_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDERS_FAILURE'

export const SHIP_ORDER_REQUEST = 'SHIP_ORDERS_REQUEST'
export const SHIP_ORDER_SUCCESS = 'SHIP_ORDERS_SUCCESS'
export const SHIP_ORDER_FAILURE = 'SHIP_ORDERS_FAILURE'





