export const RETRIVE_TOP_SELLING_REQUEST = "RETRIVE_TOP_SELLING_REQUEST"
export const RETRIVE_TOP_SELLING_SUCCESS = "RETRIVE_TOP_SELLING_SUCCESS"
export const RETRIVE_TOP_SELLING_FAILURE = "RETRIVE_TOP_SELLING_FAILURE"

export const RETRIVE_MONTHLY_REVENUE_REQUEST = "RETRIVE_MONTHLY_REVENUE_REQUEST"
export const RETRIVE_MONTHLY_REVENUE_SUCCESS = "RETRIVE_MONTHLY_REVENUE_SUCCESS"
export const RETRIVE_MONTHLY_REVENUE_FAILURE = "RETRIVE_MONTHLY_REVENUE_FAILURE"